# Generated by Django 5.0.12 on 2025-02-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'Documento Nacional de Identidad'), ('RUC', 'Registro Único de Contribuyente'), ('PASAPORTE', 'Pasaporte'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Documento')),
                ('num_documento', models.CharField(max_length=15, unique=True, verbose_name='Número de Documento')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Correo Electrónico')),
                ('estado', models.IntegerField(default=1, verbose_name='Estado')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
    ]
