# Generated by Django 5.0.12 on 2025-02-28 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_proveedor_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('stock_minimo', models.IntegerField(verbose_name='Stock Mínimo')),
                ('imagen', models.CharField(blank=True, max_length=100, null=True, verbose_name='Imagen')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estado', models.IntegerField(default=1, verbose_name='Estado')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria', verbose_name='Categoría')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proveedor', verbose_name='Proveedor')),
                ('id_unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unidadmedida', verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Material o Servicio',
                'verbose_name_plural': 'Materiales o Servicios',
                'db_table': 'materiales_servicios',
            },
        ),
    ]
