# Generated by Django 5.0.12 on 2025-03-11 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'Documento Nacional de Identidad'), ('RUC', 'Registro Único de Contribuyente'), ('PASAPORTE', 'Pasaporte'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Documento')),
                ('num_documento', models.CharField(max_length=15, verbose_name='Número de Documento')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('tiempo_contrato', models.CharField(max_length=150, verbose_name='Tiempo de Contrato')),
                ('sueldo_diario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sueldo Diario')),
                ('sueldo_semanal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sueldo Semanal')),
                ('sueldo_quincenal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sueldo Quincenal')),
                ('sueldo_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sueldo Mensual')),
                ('sueldo_proyecto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sueldo Proyecto')),
                ('estado', models.IntegerField(default=1, verbose_name='Estado')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('id_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.especialidad', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'db_table': 'trabajadores',
            },
        ),
    ]
