# Generated by Django 5.0.12 on 2025-03-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_trabajador'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('marca', models.CharField(blank=True, max_length=150, null=True, verbose_name='Marca')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('costo_hora', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo por Hora')),
                ('costo_diario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Diario')),
                ('costo_semanal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Semanal')),
                ('costo_quincenal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Quincenal')),
                ('costo_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Mensual')),
                ('costo_proyecto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Proyecto')),
                ('estado', models.IntegerField(default=1, verbose_name='Estado')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Equipo o Maquinaria',
                'verbose_name_plural': 'Equipos o Maquinarias',
                'db_table': 'equipos_maquinarias',
            },
        ),
    ]
