# Generated by Django 5.0.12 on 2025-03-12 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_equipomaquinaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncargarMaquinaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('id_equipo_maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipomaquinaria', verbose_name='Equipos Maquinarias')),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trabajador', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Encargo maquina equipo',
                'verbose_name_plural': 'Encargar máquinas y equipos',
                'db_table': 'encargar_maquina_equipo',
            },
        ),
    ]
