# Generated by Django 5.0.12 on 2025-03-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='condicion_pago',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Condición de pago'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='garantia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Garantía'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='observacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Observación'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='plazo_ejecucion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plazo de ejecución'),
        ),
    ]
