# Generated by Django 5.0.12 on 2025-03-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_presupuesto_condicion_pago_presupuesto_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante', models.CharField(blank=True, max_length=50, null=True, verbose_name='Comprobante')),
                ('serie', models.CharField(max_length=20, verbose_name='Serie')),
                ('folio_inicial', models.IntegerField(verbose_name='Folio Inicial')),
                ('folio_final', models.IntegerField(verbose_name='Folio Final')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'db_table': 'comprobantes',
            },
        ),
    ]
