# Generated by Django 5.0.12 on 2025-03-12 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='id_comprobante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comprobante', verbose_name='Comprobante'),
        ),
    ]
