# Generated by Django 5.0.12 on 2025-03-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_presupuesto_id_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
    ]
