# Generated by Django 5.0.12 on 2025-03-18 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_presupuesto_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMetrosTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Medida')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('id_presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_metros_terreno', to='app.presupuesto', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Detalle de Metros de Terreno',
                'verbose_name_plural': 'Detalles de Metros de Terreno',
                'db_table': 'detalle_metros_terreno',
            },
        ),
        migrations.CreateModel(
            name='DetallePresupuestoEquipoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_costo', models.CharField(choices=[('hora', 'Por Hora'), ('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('proyecto', 'Por Proyecto')], max_length=100, verbose_name='Tipo de Costo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('tiempo', models.IntegerField(verbose_name='Tiempo')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('id_maquina_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_presupuesto_equipo_maquina', to='app.equipomaquinaria', verbose_name='Equipo/Máquina')),
                ('id_presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_presupuesto_equipo_maquina', to='app.presupuesto', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Detalle de Presupuesto Equipo/Máquina',
                'verbose_name_plural': 'Detalles de Presupuesto Equipo/Máquina',
                'db_table': 'detalle_presupuesto_equipo_maquina',
            },
        ),
        migrations.CreateModel(
            name='DetallePresupuestoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('id_material_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_presupuesto_material', to='app.materialservicio', verbose_name='Material/Servicio')),
                ('id_presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_presupuesto_material', to='app.presupuesto', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Detalle de Presupuesto Material',
                'verbose_name_plural': 'Detalles de Presupuesto Material',
                'db_table': 'detalle_presupuesto_material',
            },
        ),
        migrations.CreateModel(
            name='DetallePresupuestoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sueldo', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('proyecto', 'Por Proyecto')], max_length=100, verbose_name='Tipo de Sueldo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('tiempo', models.IntegerField(verbose_name='Tiempo')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('id_presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_presupuesto_trabajador', to='app.presupuesto', verbose_name='Presupuesto')),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_presupuesto_trabajador', to='app.trabajador', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Detalle de Presupuesto Trabajador',
                'verbose_name_plural': 'Detalles de Presupuesto Trabajador',
                'db_table': 'detalle_presupuesto_trabajador',
            },
        ),
    ]
