# Generated by Django 5.0.12 on 2025-03-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_detallemetrosterreno_detallepresupuestoequipomaquina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('correo', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje')),
                ('estado', models.IntegerField(default=0, verbose_name='Estado')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'contactos',
            },
        ),
    ]
